on:
  workflow_dispatch:

jobs:
  job_id:
    # Add "id-token" with the intended permissions.
    permissions:
      contents: 'read'
      id-token: 'write'
    runs-on: ubuntu-latest

    steps:
      - name: Checkout actions-oidc-debugger
        uses: actions/checkout@v3
        with:
          repository: github/actions-oidc-debugger
          ref: main
          token: ${{ secrets.GITHUB_TOKEN }}
          path: ./.github/actions/actions-oidc-debugger
      - name: Debug OIDC Claims
        uses: ./.github/actions/actions-oidc-debugger
        with:
          audience: 'projects/640268614424/locations/global/workloadIdentityPools/stefan-playground-383411/providers/my-pool'
      
      - id: 'auth'
        name: 'Authenticate to Google Cloud'
        uses: 'google-github-actions/auth@v1'
        with:
          workload_identity_provider: 'projects/640268614424/locations/global/workloadIdentityPools/my-pool/providers/my-provider'
          service_account: 'github-action-test@stefan-playground-383411.iam.gserviceaccount.com'

      - name: 'Set up Cloud SDK'
        uses: 'google-github-actions/setup-gcloud@v1'
        with:
          install_components: alpha

      - name: 'gcloud info'
        run: 'gcloud info'

      - name: 'WIF Test'
        run: |
          gcloud alpha storage cp -r \
              "gs://wif-test-bucket-903233" ./corrected_result.csv

      - name: 'WIF copy test'
        run: cat ./corrected_result.csv